### ISSUE TITLE
Make it Python 3 friendly

### ISSUE THREAD

**Issue by lasers** [OliverUv/quickswitch-for-i3#6]
### VERSION
```
chris ~ $ python -V
Python 3.4.3
```
### SUCCESS
```
chris ~ $ quickswitch.py --journey
chris ~ $ quickswitch.py --scratchpad
chris ~ $ quickswitch.py --empty
chris ~ $ quickswitch.py --nextempty
chris ~ $ quickswitch.py --degap
chris ~ $ quickswitch.py --next
chris ~ $ quickswitch.py --previous
chris ~ $ quickswitch.py --urgent
```

### FAIL
```
chris ~ $ quickswitch.py
Traceback (most recent call last):
  File "/usr/bin/quickswitch.py", line 431, in <module>
    main()
  File "/usr/bin/quickswitch.py", line 415, in main
    lookup = lookup_func()
  File "/usr/bin/quickswitch.py", line 65, in get_windows
    windows = parse_for_windows(i3.get_tree(), [])
  File "/usr/bin/quickswitch.py", line 72, in parse_for_windows
    if (tree_dict.has_key("nodes") and len(tree_dict["nodes"]) > 0):
AttributeError: 'dict' object has no attribute 'has_key'
```
```
chris ~ $ quickswitch.py --move
Traceback (most recent call last):
  File "/usr/bin/quickswitch.py", line 431, in <module>
    main()
  File "/usr/bin/quickswitch.py", line 415, in main
    lookup = lookup_func()
  File "/usr/bin/quickswitch.py", line 65, in get_windows
    windows = parse_for_windows(i3.get_tree(), [])
  File "/usr/bin/quickswitch.py", line 72, in parse_for_windows
    if (tree_dict.has_key("nodes") and len(tree_dict["nodes"]) > 0):
AttributeError: 'dict' object has no attribute 'has_key'
```
```
chris ~ $ quickswitch.py --regex Lxappearance
Traceback (most recent call last):
  File "/usr/bin/quickswitch.py", line 431, in <module>
    main()
  File "/usr/bin/quickswitch.py", line 370, in main
    exit(os.EX_OK if find_window_by_regex(args.regex, args.insensitive, args.move) else os.EX_NOTFOUND)
  File "/usr/bin/quickswitch.py", line 97, in find_window_by_regex
    for title, id in get_windows().items():
  File "/usr/bin/quickswitch.py", line 65, in get_windows
    windows = parse_for_windows(i3.get_tree(), [])
  File "/usr/bin/quickswitch.py", line 72, in parse_for_windows
    if (tree_dict.has_key("nodes") and len(tree_dict["nodes"]) > 0):
AttributeError: 'dict' object has no attribute 'has_key'
```
### NOTES
Python 3.1.5 removed dict.has_key() – Use the in operator instead.
https://docs.python.org/3.1/reference/expressions.html#in

**Comment by OliverUv** [comment]
Nice and detailed! Thanks, will check this out this weekend or next.

**Comment by OliverUv** [comment]
Fixed, thanks
